### ISSUE TITLE
java.lang.IndexOutOfBoundsException with v0.6.0

### ISSUE THREAD

**Issue by manchot0** [jenkinsci/ansicolor-plugin#139]
Hi, since version 0.6.0 i have the following error on my pipeline when running a build : 

```
java.lang.IndexOutOfBoundsException
	at hudson.MarkupText.rangeCheck(MarkupText.java:276)
	at hudson.MarkupText.addMarkup(MarkupText.java:270)
	at hudson.plugins.ansicolor.ColorConsoleAnnotator$1EmitterImpl.emitHtml(ColorConsoleAnnotator.java:74)
	at hudson.plugins.ansicolor.AnsiAttributeElement.emitClose(AnsiAttributeElement.java:42)
	at hudson.plugins.ansicolor.AnsiHtmlOutputStream.closeOpenTags(AnsiHtmlOutputStream.java:107)
	at hudson.plugins.ansicolor.AnsiHtmlOutputStream.processAttributeRest(AnsiHtmlOutputStream.java:542)
	at hudson.plugins.ansicolor.AnsiOutputStream.processEscapeCommand(AnsiOutputStream.java:358)
	at hudson.plugins.ansicolor.AnsiOutputStream.write(AnsiOutputStream.java:138)
	at hudson.plugins.ansicolor.AnsiHtmlOutputStream.write(AnsiHtmlOutputStream.java:220)
	at org.apache.commons.io.output.ProxyOutputStream.write(ProxyOutputStream.java:55)
	at hudson.plugins.ansicolor.ColorConsoleAnnotator.annotate(ColorConsoleAnnotator.java:91)
	at hudson.console.ConsoleAnnotator$ConsoleAnnotatorAggregator.annotate(ConsoleAnnotator.java:108)
	at hudson.console.ConsoleAnnotationOutputStream.eol(ConsoleAnnotationOutputStream.java:148)
	at hudson.console.LineTransformationOutputStream.eol(LineTransformationOutputStream.java:60)
	at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:56)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:77)
	at org.jenkinsci.plugins.workflow.log.FileLogStorage$1$1.write(FileLogStorage.java:238)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
	at org.apache.commons.io.output.ProxyOutputStream.write(ProxyOutputStream.java:90)
	at org.kohsuke.stapler.framework.io.LargeText$HeadMark.moveTo(LargeText.java:314)
	at org.kohsuke.stapler.framework.io.LargeText.writeLogTo(LargeText.java:229)
	at hudson.console.AnnotatedLargeText.writeRawLogTo(AnnotatedLargeText.java:163)
	at org.jenkinsci.plugins.workflow.log.FileLogStorage$1.writeHtmlTo(FileLogStorage.java:203)
	at hudson.console.AnnotatedLargeText.writeLogTo(AnnotatedLargeText.java:144)
	at org.kohsuke.stapler.framework.io.LargeText.doProgressText(LargeText.java:264)
	at hudson.console.AnnotatedLargeText.doProgressiveHtml(AnnotatedLargeText.java:92)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:130)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
Caused: javax.servlet.ServletException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:789)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$3.doDispatch(MetaClass.java:212)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:384)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:253)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:253)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:253)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:243)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:745)
```
The pipeline still kept going but there is no more output on the console.
the error seems to always appear at the same step : 

```
def mavenVersion(){
ansiColor('xterm') {
     echo "\033[94;1m[ INFO ] Récupération du numéro de version de l'application\033[0m"
}
     env.APP_VERSION = sh script : 'grep "<version>" pom.xml | head -n 1 | grep -om1 "[0-9.]\\+"',returnStdout: true
}
```
but there is two output in colors displayed before like this one : 

```
def CleanAledaDependency(){
ansiColor('xterm') {
    echo "\033[94;1m[ INFO ] Nettoyage des dépendances  dans le cache maven et gradle\033[0m"
}
    sh 'rm -rf /home/jenkins/.m2/repository/xxx/* & rm -rf /home/jenkins/.gradle/caches/modules-2/files-2.1/xxx/*'
}
```

I am on Jenkins 2.152 with the multibranch pipeline. I have reverted back to the 0.5.3 version of the plugin.

**Comment by navrkald** [comment]
I had same issue and can confirm downgrade to 0.5.3 helped!

**Comment by Dukecz** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-54752

**Comment by aaratushnyak** [comment]
I had same issue

**Comment by igiu1988** [comment]
i had same issue 0.6.0. 0.5.2 is good

**Comment by dwnusbaum** [comment]
I think the code is broken for any annotated line with more than 1 multi-byte character such as `é` (I'm not yet sure why there is one character of leeway, maybe MarkupText allows insertions at the end of the text). We count bytes as we process input and use that to produce offsets for where to insert HTML markup, but the HTML markup is a Java-level string, and so `é` gets counted as 2 bytes, but at the Java level it is a single character, so our offset calculations are wrong and we overshoot the end of the string in some cases.

**Comment by dwnusbaum** [comment]
I think this would be fixed by a2a74eb8 which I just pushed in #137. I will try to separate that change from the other bug fixes in that PR sometime today so it can be merged/released independently.

**Comment by kraduk** [comment]
I was also getting this issue when used in conjunction with the ansible playbook. Rolling back the ansicolour to 0.5.2 does indeed fix the issue

**Comment by jkugler** [comment]
@navrkald and @kraduk How do I roll back? The releases seem to be all source, no binaries. I don't have a way to compile plugins right now, and I don't see a way to specify the version in the Jenkins Plugin Installer. Pointers/docs/etc welcome.

**Comment by dblock** [comment]
Sorry for the hassle everyone. I have't been using Jenkins much so I am going to leave the proposed fixes to @jglick and @dwnusbaum to sort out, merge and release. Will jump in if one is unavailable or something like that this week.

**Comment by dwnusbaum** [comment]
A fix for this issue was just released in ansicolor 0.6.1.

**Comment by RishabhTayal** [comment]
I can confirm this issue is fixed. I was having this issue in 0.6.0, after upgrading to 0.6.1 it's fixed. 💯

**Comment by shreknitin89** [comment]
@dwnusbaum This is still happening on 0.6.2. After the build is finished sometimes we get the complete logs but in some cases gets the truncated logs.

While the build is running at some point in the logs we get the same exception.

**Comment by dwnusbaum** [comment]
@shreknitin89 The exception might be the same, but your stack trace looks distinct from the one reported in this ticket. I would open a new issue, preferably including a minimal subset of your logs that reproduces the problem.

**Comment by shreknitin89** [comment]
Ok @dwnusbaum. I opened https://github.com/jenkinsci/ansicolor-plugin/issues/158 for the same
