### ISSUE TITLE
Very frequent 1 byte write (poor performance, high cpu usage)

### ISSUE THREAD

**Issue by afazekas** [jenkinsci/ansicolor-plugin#144]
Please provide precise details of the issue you detected.

### Test environment

- Jenkins Version:  2.89.4
- AnsiColor Version: 0.5.2  (The relevant code part looks the same on master)
- Hostsystem: openjdk 1.8.0.171-7.b10.el7 Linux

### Expected behavior

The log file written in >10 bye average quantities (per line) .

### Actual behavior

strace output of log writing thread:

write(2722, "N", 1)                     = 1
write(2722, "k", 1)                     = 1
write(2722, "h", 1)                     = 1
write(2722, "O", 1)                     = 1
write(2722, "t", 1)                     = 1
write(2722, "l", 1)                     = 1
write(2722, "a", 1)                     = 1
write(2722, "y", 1)                     = 1
write(2722, "A", 1)                     = 1
write(2722, "w", 1)                     = 1
write(2722, "D", 1)                     = 1
write(2722, "j", 1)                     = 1
write(2722, "l", 1)                     = 1
write(2722, "A", 1)                     = 1
write(2722, "F", 1)                     = 1
write(2722, "c", 1)                     = 1
write(2722, "o", 1)                     = 1
write(2722, "g", 1)                     = 1
write(2722, "A", 1)                     = 1
write(2722, "A", 1)                     = 1
write(2722, "A", 1)                     = 1
write(2722, "A", 1)                     = 1
write(2722, "=", 1)                     = 1
write(2722, "=", 1)                     = 1
write(2722, "\33[0m", 4)                = 4

Relevant thread:
"Computer.threadPoolForRemoting [#113211] : IO ID=964106 : seq#=964105" #18002953 daemon prio=5 os_prio=0 tid=0x00007f88a421e5a0 nid=0x2ccc runnable [0x00007f87f545a000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileOutputStream.write(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:290)
        at hudson.plugins.ansicolor.AnsiHtmlOutputStream.write(AnsiHtmlOutputStream.java:229)
        at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
        at hudson.plugins.ansicolor.AnsiColorConsoleLogFilter$1.eol(AnsiColorConsoleLogFilter.java:51)
        at hudson.console.LineTransformationOutputStream.eol(LineTransformationOutputStream.java:60)
        at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:56)
        at hudson.plugins.ansicolor.AnsiOutputStream.write(AnsiOutputStream.java:87)
        at hudson.plugins.ansicolor.AnsiHtmlOutputStream.write(AnsiHtmlOutputStream.java:220)
        at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
        at hudson.plugins.ansicolor.AnsiColorConsoleLogFilter$1.eol(AnsiColorConsoleLogFilter.java:51)
        at hudson.console.LineTransformationOutputStream.eol(LineTransformationOutputStream.java:60)
        at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:56)
        at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:74)
        at java.io.PrintStream.write(PrintStream.java:480)
        - locked <0x000000064950d200> (a java.io.PrintStream)
        at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
        at hudson.remoting.ProxyOutputStream$Chunk$1.run(ProxyOutputStream.java:256)
        at hudson.remoting.PipeWriter$1.run(PipeWriter.java:158)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
        at org.jenkinsci.remoting.CallableDecorator.call(CallableDecorator.java:19)
        at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

The not buffered FileOutputStream directly used for writing logs, the write is frequently called with a single character:
https://github.com/jenkinsci/ansicolor-plugin/blob/3f094600537bd76d4503864cb44d3d9c4ca450eb/src/main/java/hudson/plugins/ansicolor/AnsiHtmlOutputStream.java#L229

Regardless how fast is your storage, this type of 1 byte write will produce less 1MB/sec log write with a very high CPU usage.

Please try to use some kind of buffering and make sure bigger chunks (typically at least 1 line) is being written at all file write call.

**Comment by afazekas** [comment]
The 0.5.3 still has the issue, but 0.6.0 does not seams to have the issue however, it requires very new jenkins.
